# These are supported funding model platforms

# GitHub Sponsors (GitHub username)
github: kpeacocke
# Open Collective (project name)
# open_collective: gh-deployer

# Ko-fi (username)
# ko_fi: kpeacocke

# Buy Me a Coffee (username)
# buy_me_a_coffee: kpeacocke

# Patreon (username)
# patreon: kpeacocke

# Custom funding URLs
# custom: ['https://paypal.me/kpeacocke', 'https://www.buymeacoffee.com/kpeacocke']
